[package]
name = "kata"
version = "0.1.0"
edition = "2021"
description = "String templating engine for Rust"
repository = "https://github.com/Twometer/kata"
license = "MIT"
authors = ["Twometer"]

[lib]
name = "kata"
path = "src/kata/lib.rs"

[dependencies]